/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Resources.ModelAdapter;
import Resources.RoomDescription;
import Resources.SQLiteJDBC;
import hotelmanager.Hotel;
import hotelmanager.Room;
import hotelmanager.UserInformation;
import java.text.DateFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.ListIterator;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;

/**
 *
 * @author PikeMobile
 */
public class CustomerMainWindow extends javax.swing.JFrame {

    private SQLiteJDBC database = SQLiteJDBC.getInstance();
    //private final UserInformation guest = new UserInformation("Guest", "Guest", "", "Guest", "Customer");
    //private UserInformation user = guest;
    //private DefaultListModel model = null;
    static private UserInformation user = null;
    private Hotel hotel = Hotel.getInstance();
    private ArrayList<Room> roomList = null;
    RoomDescription describe = new RoomDescription();
//    UtilDateModel model = new UtilDateModel();
//JDatePanelImpl datePanel = new JDatePanelImpl(model);
//JDatePickerImpl datePicker = new JDatePickerImpl(datePanel);
// 
//    add(datePicker);
    /**
     * Creates new form CustomerMainWindow
     * @param 
     */
    public CustomerMainWindow(UserInformation aUser) {
        initComponents();
        database = SQLiteJDBC.getInstance();
        user = aUser;
        firstNameLabel.setText(user.GetFirstName());
        roomList = hotel.searchAllRooms();
        //ListIterator room = roomList.listIterator(); 
//        while(room.hasNext())
//        //for(Room temp : rooms)
//        {
//            Room temp = (Room)room.next();
//            System.out.println(temp.toString());
//        }
        
        this.update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoutButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        reserveButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        smokingCheckBox = new javax.swing.JCheckBox();
        twoBedCheckBox = new javax.swing.JCheckBox();
        queenBedCheckBox = new javax.swing.JCheckBox();
        StartMonth = new javax.swing.JComboBox();
        StartDay = new javax.swing.JComboBox();
        StartYear = new javax.swing.JComboBox();
        EndMonth = new javax.swing.JComboBox();
        EndDay = new javax.swing.JComboBox();
        EndYear = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        logoutMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Hello:");

        firstNameLabel.setText("First Name");

        jButton1.setText("Search Room");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        reserveButton.setText("Reserve Room");
        reserveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveButtonActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        smokingCheckBox.setText("Smoking");
        smokingCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smokingCheckBoxActionPerformed(evt);
            }
        });

        twoBedCheckBox.setText("Two Beds");

        queenBedCheckBox.setText("Queen Bed");

        StartMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        StartMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartMonthActionPerformed(evt);
            }
        });

        StartDay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        StartDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartDayActionPerformed(evt);
            }
        });

        StartYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Year", "2015", "2016", "2017", "2018", "2019", "2020" }));

        EndMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        EndDay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        EndYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Year", "2015", "2016", "2017", "2018", "2019", "2020" }));

        jLabel2.setText("Start Date");

        jLabel3.setText("End Date");

        jMenu1.setText("File");

        logoutMenu.setText("Logout");
        logoutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuActionPerformed(evt);
            }
        });
        jMenu1.add(logoutMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Room Options");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reserveButton)
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(smokingCheckBox)
                        .addGap(30, 30, 30)
                        .addComponent(twoBedCheckBox)
                        .addGap(35, 35, 35)
                        .addComponent(queenBedCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 345, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(154, 154, 154)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(logoutButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EndMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(EndDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(EndYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(StartMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(StartDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(StartYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutButton)
                    .addComponent(jLabel1)
                    .addComponent(firstNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 629, Short.MAX_VALUE)
                .addComponent(reserveButton)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(smokingCheckBox)
                    .addComponent(twoBedCheckBox)
                    .addComponent(queenBedCheckBox))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StartMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StartDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StartYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(EndMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EndDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EndYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuActionPerformed
        // TODO add your handling code here:
        hotel.saveState();
        user.logout();
    }//GEN-LAST:event_logoutMenuActionPerformed

    public void update()
    {
        if(roomList.size()>=0)
        {
            jList1.setModel(new ModelAdapter(roomList));
        }
        
    }
    
    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        hotel.saveState();
        user.logout();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void reserveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveButtonActionPerformed
        try {
            // TODO add your handling code here:
            int index = jList1.getSelectedIndex();
            if(roomList.size() >= 0)
            {
                Room temp = (Room)roomList.get(index);
                Date Start = new Date();
                Date End = new Date();
                Start.setYear(Integer.parseInt(StartYear.getSelectedItem().toString()));
                Start.setMonth(StartMonth.getSelectedIndex());
                Start.setDate(StartDay.getSelectedIndex());
                End.setYear(Integer.parseInt(EndYear.getSelectedItem().toString()));
                End.setMonth(EndMonth.getSelectedIndex());
                End.setDate(EndDay.getSelectedIndex());
                
                hotel.makeReservation(Start,End,temp.getRoomNum(),false,user.GetEmailAddress()) ;
            }
        } catch (Exception e) {
            Logger.getLogger(CustomerMainWindow.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_reserveButtonActionPerformed

    private void smokingCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smokingCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smokingCheckBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int total = 0;
        if(smokingCheckBox.isSelected())
        {
            total += describe.smoke;
        }
        if(queenBedCheckBox.isSelected())
        {
            total += describe.queenBed;
        }
        if(twoBedCheckBox.isSelected())
        {
            total += describe.twobeds;
        }
        roomList = hotel.searchRooms(total);
        this.update();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void StartMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StartMonthActionPerformed

    private void StartDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StartDayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerMainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerMainWindow(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox EndDay;
    private javax.swing.JComboBox EndMonth;
    private javax.swing.JComboBox EndYear;
    private javax.swing.JComboBox StartDay;
    private javax.swing.JComboBox StartMonth;
    private javax.swing.JComboBox StartYear;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JMenuItem logoutMenu;
    private javax.swing.JCheckBox queenBedCheckBox;
    private javax.swing.JButton reserveButton;
    private javax.swing.JCheckBox smokingCheckBox;
    private javax.swing.JCheckBox twoBedCheckBox;
    // End of variables declaration//GEN-END:variables
}
